import React, { useState, useEffect } from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFViewer,pdf
} from "@react-pdf/renderer";
import saveAs from 'file-saver';

// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: "white",
    color: "black",
    padding: 20,
  },
  section: {
    flexDirection: 'row',
    borderBottom: 1,
    borderBottomColor: '#808080',
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingBottom: 10,
  },
  viewer: {
    width: window.innerWidth, //the pdf viewer will take up all of the width and height
    height: window.innerHeight,
  },
  heading: {
    fontSize: 16,
    textAlign: 'center',
  },
  userDetails: {
    fontSize: 14,
    fontWeight: 1000,
    color: '#000080',
    marginTop: 20,
    marginBottom: 8,
  },
  address: {
    fontSize: 10,
  }
});

// Create Document Component 
export default function CertificateForFile() {
  const [loginUseremail, setLoginUseremail] = useState();
  const [chatUseremail, setChatUseremail] = useState();
  const [loginUsername, setLoginUsername] = useState();
  const [chatUsername, setChatUsername] = useState();
  const [dateTime, setDateTime] = useState();

  useEffect(async () => {
    const loginUser1 = JSON.parse(localStorage.getItem('chat-app-current-user'));
    setLoginUseremail(loginUser1.email);
    setLoginUsername(loginUser1.username);
    const chatUser = JSON.parse(localStorage.getItem('current-chat-with'));
    setChatUsername(chatUser.username);
    setChatUseremail(chatUser.email);
    setDateTime(localStorage.getItem('dateTimeFile'));

    const blob = await pdf((
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.heading}> Certificate Generated By VAULTIO</Text>

          <Text style={styles.userDetails}>File Details</Text>

          <View style={styles.section}>
            <Text style={styles.address}>Sender Username</Text>
            <Text style={styles.address}>{loginUsername}</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.address}>Sender Email</Text>
            <Text style={styles.address}>{chatUsername}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Username</Text>
            <Text style={styles.address}>{loginUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Email</Text>
            <Text style={styles.address}>{chatUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Date & Time</Text>
            <Text style={styles.address}>{dateTime}</Text>
          </View>
        </Page>
      </Document>
    )).toBlob();
    saveAs(blob, 'certificate.pdf');
  }, [])

  return (
    <PDFViewer style={styles.viewer}>
      <Document>
        <Page size="A4" style={styles.page}>
          <Text style={styles.heading}> Certificate Generated By VAULTIO</Text>

          <Text style={styles.userDetails}>File Details</Text>

          <View style={styles.section}>
            <Text style={styles.address}>Sender Username</Text>
            <Text style={styles.address}>{loginUsername}</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.address}>Sender Email</Text>
            <Text style={styles.address}>{chatUsername}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Username</Text>
            <Text style={styles.address}>{loginUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Email</Text>
            <Text style={styles.address}>{chatUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Date & Time</Text>
            <Text style={styles.address}>{dateTime}</Text>
          </View>
        </Page>
      </Document>
    </PDFViewer>
  );
}